// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SqlClientTypeProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("SqlClientTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This is a type provider to generate sql queries from MS Sql Server")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SqlClientTypeProvider.Runtime"
    let [<Literal>] AssemblyProduct = "SqlClientTypeProvider"
    let [<Literal>] AssemblyDescription ="This is a type provider to generate sql queries from MS Sql Server"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"